# Site settings

baseurl: "https://thequib.github.io"
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: QuibTech

permalinks:
  post: /p/:slug/
  page: /:slug/


# Language preferences

languages:
  en:
    languageName: English
    title: QuibTech
    weight: 1

DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false


disqusShortname: quibtech


# site parameters

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: images/logo.png

  footer:
    since: 2021
    customText: i do tech.

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    #emoji: ☕
    subtitle: i do tech.
    avatar:
      enabled: true
      local: true
      src: img/avatar.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: false
    provider: disqus

    disqusjs:
      shortname: quibtech-thequib
      apiUrl:
      apiKey:
      admin:
      adminLabel:

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: tag-cloud
        params:
          limit: 10
      - type: categories
        params:
          limit: 10
    page:
      - type: toc

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main: []

  social:
    - identifier: buymeacoffee
      name: Buy Me a Coffee
      url: https://buymeacoffee.com/quinnhenry
      params:
        icon: brand-buymeacoffee

    - identifier: github
      name: GitHub
      url: https://github.com/CaiJimmy/hugo-theme-stack
      params:
        icon: brand-github

    - identifier: linkedin
      name: linkedin
      url: https://www.linkedin.com/in/quinn-henry/
      params:
        icon: brand-linkedin

    - identifier: instagram
      name: Instagram
      url: https://instagram.com/brit_boi_
      params:
        icon: brand-instagram

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4